// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTee8uqLVp4EHmcFFSj4Wizf8EVQ4BVSQ',
    appId: '1:166074631675:web:91dd931ea16983409df75e',
    messagingSenderId: '166074631675',
    projectId: 'privatesnotes-flutter-apps',
    authDomain: 'privatesnotes-flutter-apps.firebaseapp.com',
    storageBucket: 'privatesnotes-flutter-apps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2VIL3NLzNxDC10XvnVad2kEWLtoSOzf8',
    appId: '1:166074631675:android:89741a16d63f69eb9df75e',
    messagingSenderId: '166074631675',
    projectId: 'privatesnotes-flutter-apps',
    storageBucket: 'privatesnotes-flutter-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd096-nKUFC0bWkatml6mCsfAN3Vw8PJQ',
    appId: '1:166074631675:ios:0ab514dacc5059ad9df75e',
    messagingSenderId: '166074631675',
    projectId: 'privatesnotes-flutter-apps',
    storageBucket: 'privatesnotes-flutter-apps.appspot.com',
    iosBundleId: 'com.example.privatenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd096-nKUFC0bWkatml6mCsfAN3Vw8PJQ',
    appId: '1:166074631675:ios:0ab514dacc5059ad9df75e',
    messagingSenderId: '166074631675',
    projectId: 'privatesnotes-flutter-apps',
    storageBucket: 'privatesnotes-flutter-apps.appspot.com',
    iosBundleId: 'com.example.privatenotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTee8uqLVp4EHmcFFSj4Wizf8EVQ4BVSQ',
    appId: '1:166074631675:web:540bf45438683bfd9df75e',
    messagingSenderId: '166074631675',
    projectId: 'privatesnotes-flutter-apps',
    authDomain: 'privatesnotes-flutter-apps.firebaseapp.com',
    storageBucket: 'privatesnotes-flutter-apps.appspot.com',
  );
}
